### ISSUE TITLE
creating pattern with number adds a dash?

### ISSUE THREAD

**Issue by rebmullin** [pattern-library/generator-pattern-library#10] opened 2015-09-29 18:50 UTC
@scottnath  - really not sure if this a big issue or realistic use case (patterns with numbers..?) but when i add a pattern with a number to it, it adds an unexpected dash:

``````
yo pattern-library:pattern
? What is the name of this Pattern? hello2
? In what category does this pattern belong? Molecules
? In what subcategory does this pattern belong? hello2
? What type of pattern is this? HTML
? Which supporting files should be included? (select with spacebar) 
   create patterns/molecules/hello-2/hello-2/hello-2.html
   create patterns/molecules/hello-2/hello-2/README.md
   create patterns/molecules/hello-2/hello-2/pattern.yml```

or see http://grab.by/KN1G
``````

**Comment by scottnath** [comment] 2015-09-29 19:19
@rebmullin 
that is due to the camelCase switching that's happening. It separates out the 2 as though it's a different word. This is working as expected.

Is there a solid use case to _not_ have this happen?

**Comment by rebmullin** [comment] 2015-09-29 20:11
no it just happened when i was testing out the clone (cloned h1) and saw this...
if this is not an issue, then we can close this : )

**Comment by scottnath** [comment] 2015-09-29 20:13
yeah...not a bug - expected result.

closing issue. thanks!

**Closed as completed by scottnath** 2015-09-29 20:13 UTC
